# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: postPara3DKeyPoints.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='postPara3DKeyPoints.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x19postPara3DKeyPoints.proto\"-\n\x07\x43\x33\x44Para\x12\x10\n\x08wShpBase\x18\x01 \x03(\x02\x12\x10\n\x08wExpBase\x18\x02 \x03(\x02'
)




_C3DPARA = _descriptor.Descriptor(
  name='C3DPara',
  full_name='C3DPara',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wShpBase', full_name='C3DPara.wShpBase', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wExpBase', full_name='C3DPara.wExpBase', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['C3DPara'] = _C3DPARA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

C3DPara = _reflection.GeneratedProtocolMessageType('C3DPara', (_message.Message,), {
  'DESCRIPTOR' : _C3DPARA,
  '__module__' : 'postPara3DKeyPoints_pb2'
  # @@protoc_insertion_point(class_scope:C3DPara)
  })
_sym_db.RegisterMessage(C3DPara)


# @@protoc_insertion_point(module_scope)
